services:
  db:
    image: mariadb:11.2.4
    container_name: notesmd-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tester
      MYSQL_DATABASE: notesmd
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: notesmd-phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: notesmd-db